#!/bin/python
from pathlib import Path
from sys import argv
left_file, right_file = Path(argv[1]).read_text(), Path(argv[2]).read_text()
out = 0
ignored_keys = ["TRACKID", "EGUID"]

if len(left_file) != len(right_file):
    print("Different sizes")
    out = 1

# skip project declaration
for left, right in zip(left_file.split()[1:], right_file.split()[1:]):
    left, right = left.strip(), right.strip()
    if left == right or any(map(lambda x: left.startswith(x), ignored_keys)):
        continue
    out = 1

exit(out)
