#!/bin/python
from pathlib import Path
from sys import argv
left_file, right_file = Path(argv[1]).read_text(), Path(argv[2]).read_text()
out = 0
ignored_keys = Path("ignored_keys").read_text().split()

# skip project declaration
for left, right in zip(left_file.split("\n")[1:], right_file.split("\n")[1:]):
    left, right = left.strip(), right.strip()
    if left.startswith("MARKER") and right.startswith("MARKER"):  # marker id
        left, right = left[:left.find("{")], right[:right.find("{")]
    if left == right or any(map(lambda x: left.startswith(x), ignored_keys)):
        continue
    # binary state may differ slightly
    if len(left) == len(right) and sum(x != y for x, y in zip(left, right)) < 5:
        continue
    print(f"< {left}\n> {right}")
    out = 1

exit(out)
