#!/bin/sh
ret=0; reaper="./reaper/reaper -new -nosplash"
[ $# -eq 0 ] && timeout 6 $reaper 1>/dev/null 2>&1 # still evaluating

for test in $(shuf -e ${1:-*.rks}); do
    out="output-${test}"
    [ $# -eq 0 ] && echo $test
    $reaper -saveas $out 1>/dev/null 2>&1 &
    pid=$(echo $!); sleep 1
    xdotool search --onlyvisible --all reaper windowfocus 1>/dev/null 2>&1

    { <$test sed 's|"[^"]*$||' | tr ' ' '\n'
    } | while read cmd; do
        if [ "${cmd%${cmd#?}}" = "&" ]; then
            xdotool key "${cmd#?}"
        else
            xdotool type "$cmd"
        fi
        [ $# -eq 2 ] && sleep .3
        case $test in
            slow*) sleep .08;;
            *) sleep .01;;
        esac
    done

    xdotool type " ps"; sleep .2
    [ $# -eq 2 ] || kill $pid

    ./compare ${test%.rks}.RPP $out
    diff_ret=$(echo $?)
    ret=$(( ret + diff_ret ))
done
exit $ret
