return {
  meta_command = {
    ["."] = "RepeatLastCommand",
    ["@"] = "PlayMacro",
    ["q"] = "RecordMacro",
  },
  register_action = {
    ['"'] = "PasteRegister",
    ["yf"] = "SaveFxChain",
  },
  timeline_motion = {
    ["["] = "GoToLoopStart",
    ["]"] = "GoToLoopEnd",
    ["0"] = "GoProjectBeginning",
    ["f"] = "MoveEditCursorToPlayCursor",
    ["<M-f>"] = "MoveEditCursorToMouse",
    ["<C-f>"] = "MoveEditCursorToMouseAndSnap",
    ["<M-H>"] = "CursorLeft40",
    ["<M-L>"] = "CursorRight40",
    ["<M-h>"] = "CursorLeft10",
    ["<M-l>"] = "CursorRight10",
    ["H"] = "PrevMeasure",
    ["L"] = "NextMeasure",
    ["<C-H>"] = "Prev4Measures",
    ["<C-L>"] = "Next4Measures",
    ["h"] = "PrevBeat",
    ["l"] = "NextBeat",
    ["<C-h>"] = "Prev4Beats",
    ["<C-l>"] = "Next4Beats",
  },
  timeline_operator = {
    ["c"] = "Change",
    ["t"] = "PlaySelection",
    ["z"] = "ZoomTimeSelection",
  },
  visual_timeline_command = {
    ["o"] = "SwitchTimelineSelectionSide",
  },
  visual_track_command = {
    ["o"] = "SwitchTrackSelectionSide",
  },
  command = {
    ["T"] = "Play",
    ["F"] = "PlayPause",
    ["<M-F>"] = "MoveEditCursorToMouseAndPlay",
    ["<C-F>"] = "MoveEditCursorToMouseAndPlaySnap",
    ["<M-t>"] = "PlayFromMouse",
    ["<C-t>"] = "StartStop",
    ["<SPC>v"] = "ToggleLoop",
    ["<C-,>"] = "OpenReaperKeysConfig",
    ["v"] = "ToggleVisualTimelineMode",
    ["<M-l>"] = "MidiLearnLastTouchedFX",
    ["<M-m>"] = "ShowEnvelopeModulationLastTouchedFx",
    ["<M-s>"] = "FxToggleShowAll",
    ["<C-N>"] = "FxShowPrevSel",
    ["<C-c>"] = "ToggleFloatingWindows",
    ["<C-g>"] = "FocusMain",
    ["<C-n>"] = "FxShowNextSel",
    ["<C-p>"] = "FxShowPrevSel",
    ["<C-r>"] = "Redo",
    ["C"] = "ChangeUntilEnd",
    ["u"] = "Undo",
  },
}
