return {
  register_action = {},
  meta_command = {
    ["."] = "RepeatLastCommand",
    ["@"] = "PlayMacro",
    ["q"] = "RecordMacro",
    ["<SPC>h"] = "ShowReaperKeysHelp",
  },
  timeline_motion = {
    ["0"] = "ProjectStart",
    ["<C-$>"] = "ProjectEnd",
    ["f"] = "PlayPosition",
    ["["] = "TimeSelectionStart",
    ["]"] = "TimeSelectionEnd",
    ["<left>"] = "PrevMarker",
    ["<right>"] = "NextMarker",
    ["x"] = "MouseAndSnap",
    ["X"] = "Mouse",
    ["<M-h>"] = "Left10Pix",
    ["<M-l>"] = "Right10Pix",
    ["<M-H>"] = "Left40Pix",
    ["<M-L>"] = "Right40Pix",
    ["h"] = "PrevBeat",
    ["l"] = "NextBeat",
    ["H"] = "PrevMeasure",
    ["L"] = "NextMeasure",
    ["<C-h>"] = "Prev4Beats",
    ["<C-l>"] = "Next4Beats",
    ["<C-H>"] = "Prev4Measures",
    ["<C-L>"] = "Next4Measures",
  },
  timeline_operator = {
    ["<M-r>"] = "Record",
    ["r"] = "RecordByReplacing",
    ["c"] = "RecordByChanging",
    ["a"] = "RecordByAppending",
    ["t"] = "Play",
    ["z"] = "ZoomSelHorizontal",
  },
  timeline_selector = {
    ["v"] = "Selection",
    ["i"] = {"+inner", {
               ["<M-w>"] = "AutomationItem",
               ["r"] = "MarkerRegion",
               ["l"] = "AllTrackItems",
               ["p"] = "Project",
               ["w"] = "Item",
               ["W"] = "BigItem",
    }},
    ["n"] = "NextRegion",
    ["N"] = "PrevRegion",
  },
  visual_timeline_command = {
    ["v"] = "SetModeNormal",
    ["o"] = "SwitchTimelineSelectionSide",
  },
  command = {
    ["R"] = "ToggleRecord",
    ["T"] = "TransportPlay",
    ["F"] = "TransportPause",
    ["C"] = "ToggleRecordConditional",
    ["A"] = "GoToLastItemAndRecord",
    ["v"] = "SetModeVisualTimeline",
    ["<C-i>"] = "ZoomRedo",
    ["<C-o>"] = "ZoomUndo",
    ["<M-i>"] = "MoveRedo",
    ["<M-o>"] = "MoveUndo",
    ["("] = "SetTimeSelectionStart",
    [")"] = "SetTimeSelectionEnd",
    ["<C-SPC>"] = "ToggleViewMixer",
    ["<ESC>"] = "Reset",
    ["<C-r>"] = "Redo",
    ["<return>"] = "StartStop",
    ["u"] = "Undo",
    ["<M-T>"] = "MoveToMouseAndPlay",
    ["<M-t>"] = "PlayFromMouse",
    ["<C-t>"] = "StartStop",
    ["<M-f>"] = "MidiLearnLastTouchedFX",
    ["<M-m>"] = "ShowEnvelopeModulationLastTouchedFx",
    ["<M-g>"] = "FocusMain",
    ["<M-x>"] = "FxToggleShow",
    ["<M-X>"] = "FxClose",
    ["<M-n>"] = "FxShowNextSel",
    ["<M-N>"] = "FxShowPrevSel",
    ["<SPC>"] = { "+leader commands", {
      ["<SPC>"] = "ShowActionList",
      ["h"] = "ShowReaperKeysHelp",
      ["r"] = {"+regions", {
                 ["i"] = "InsertRegion",
                 ["d"] = "DeleteRegion",
      }},
      ["m"]= { "+markers", {
                ["n"] = "NextMarker",
                ["N"] = "PrevMarker",
      }},
      ["i"] = { "+items", {
                  ["j"] = "NextTake",
                  ["ci"] = "CycleItemFadeInShape",
                  ["co"] = "CycleItemFadeOutShape",
                  ["k"] = "PrevTake",
                  ["d"] = "DeleteActiveTake",
                  ["s"] = "CropToActiveTake",
                  ["e"] = "OpenMidiEditor",
                  ["n"] = "ItemNormalize",
                  ["r"] = "ItemApplyFX",
                  ["g"] = "GroupItems",
      }},
      ["t"] = { "+track", {
                  ["<ESC>"] = "ResetTrackToNormal",
                  ["R"] = "RenderTrack",
                  ["s"] = "ToggleSolo",
                  ["m"] = "ToggleMute",
                  ["i"] = "AddTrackVirtualInstrument",
                  ["c"] = "RenameTrack",
                  ["M"] = "CycleRecordMonitor",
                  ["x"] = {"+routing", {
                             ["i"] = "TrackSetInputToMatchFirstSelected",
                             ["s"] = "ShowTrackRouting",
                  }},
                  ["r"] = { "+recording", {
                              ["o"] = "SetTrackRecMidiOutput",
                              ["d"] = "SetTrackRecMidiOverdub",
                              ["t"] = "SetTrackRecMidiTouchReplace",
                              ["r"] = "SetTrackRecMidiReplace",
                              ["m"] = "SetTrackRecMonitorOnly",
                              ["i"] = "SetTrackRecInput",
                  }},
                  ["F"] = { "+freeze", {
                    ["f"] = "FreezeTrack",
                    ["u"] = "UnfreezeTrack",
                    ["s"] = "ShowTrackFreezeDetails"
                  }},
                  ["e"] = { "+envelopes", {
                              ["s"]  = "ToggleShowAllEnvelope",
                              ["a"] = "ToggleArmAllEnvelopes",
                              ["A"] = "UnarmAllEnvelopes",
                              ["d"] = "ClearAllEnvelope",
                              ["v"] = "ToggleVolumeEnvelope",
                              ["p"] = "TogglePanEnvelope",
                  }},
      }},
      ["a"] = { "+automation", {
                  ["r"] = "SetAutomationModeTrimRead",
                  ["R"] = "SetAutomationModeRead",
                  ["g"] = "SetAutomationModeLatchAndArm",
                  ["l"] = "SetAutomationModeLatch",
                  ["p"] = "SetAutomationModeLatchPreview",
                  ["t"] = "SetAutomationModeTouch",
                  ["c"] = "SetAutomationModeTouchAndArm",
                  ["w"] = "SetAutomationModeWrite",
      }},
      ["e"] = {"+envelope", {
                 ["a"] = "ToggleArmEnvelope",
                 ["d"] = "ClearEnvelope",
                 ["y"] = "CopyEnvelope",
                 ["t"] = "ToggleShowSelectedEnvelope",
                 ["s"] = {"+shape", {
                            ["b"] = "SetEnvelopeShapeBezier",
                            ["e"] = "SetEnvelopeShapeFastEnd",
                            ["f"] = "SetEnvelopeShapeFastStart",
                            ["l"] = "SetEnvelopeShapeLinear",
                            ["s"] = "SetEnvelopeShapeSlowStart",
                            ["S"] = "SetEnvelopeShapeSquare",
                 }},
      }},
      ["f"] = { "+fx", {
                  ["a"] = "FxAdd",
                  ["b"] = "TrackToggleFXBypass",
                  ["c"] = {"+chain", {
                            ["s"] = "FxChainToggleShow",
                            ["i"] = "ViewFxChainInputCurrentTrack",
                            ["di"] = "ClearFxChainInputCurrentTrack",
                            ["d"] = "ClearFxChainCurrentTrack",
                            ["y"] = "CopyFxChain",
                            ["p"] = "PasteFxChain",
                  }},
                  ["s"] = {"+toggle show", {
                             ["n"] = "FxShowNextSel",
                             ["N"] = "FxShowPrevSel",
                             ["c"] = "FxClose",
                             ["s"] = "FxToggleShow",
                             ["1"] = "FxToggleShow1",
                             ["2"] = "FxToggleShow2",
                             ["3"] = "FxToggleShow3",
                             ["4"] = "FxToggleShow4",
                             ["5"] = "FxToggleShow5",
                             ["6"] = "FxToggleShow6",
                             ["7"] = "FxToggleShow7",
                             ["8"] = "FxToggleShow8",
                  }},
      }},
      [","] = {"+options", {
                 ["v"] = "ToggleLoop",
                 ["s"] = "ToggleSnap",
                 ["r"] = {"+recording", {
                            ["p"] = "ToggleRecordingPreroll",
                            ["n"] = "SetRecordModeNormal",
                            ["z"] = "ToggleRecordingAutoScroll",
                 }},
                 ["c"] = "CycleRippleEditMode",
                 ["m"] = "ToggleMetronome",
                 ["t"] = "ToggleStopAtEndOfTimeSelectionIfNoRepeat",
                 ["i"] = "ToggleAutoCrossfade",
                 ["zt"] = "TogglePlaybackAutoScroll",
                 ["e"] = "ToggleEnvelopePointsMoveWithItems",
      }},
      ["m"] = {"+midi", {
                 ["s"] = "ToggleMidiSnap",
                 ["q"] = "Quantize",
                 ["z"] = "MidiZoomContent",
      }},
      ["g"] = { "+global", {
                  ["s"] = {"+show", {
                             ["x"] = "ShowRoutingMatrix",
                             ["w"] = "ShowWiringDiagram",
                             ["t"] = "ShowTrackManager",
                             ["p"] = "Preferences",
                  }},
                  ["A"] = "ClearAllRecordArm",
                  ["dr"] = "ResetControlDevices",
                  ["f"] = {"+fx", {
                             ["x"] = "FxCloseAll",
                             ["c"] = "ViewFxChainMaster",
                  }},
                  ["t"] = { "+track", {
                      ["e"] = { "+envelope", {
                              ["s"] = "ToggleShowAllEnvelopeGlobal",
                      }},
                      ["s"] = "UnsoloAllTracks",
                      ["m"] = "UnmuteAllTracks",
                  }},
                  ["a"] = { "+automation", {
                              ["r"] = "SetGlobalAutomationModeTrimRead",
                              ["l"] = "SetGlobalAutomationModeLatch",
                              ["p"] = "SetGlobalAutomationModeLatchPreview",
                              ["t"] = "SetGlobalAutomationModeTouch",
                              ["R"] = "SetGlobalAutomationModeRead",
                              ["w"] = "SetGlobalAutomationModeWrite",
                              ["S"] = "SetGlobalAutomationModeOff",
                  }},
      }},
      ["p"] = { "+project", {
                ["r"] = { "+render", {
                            ["."] = "RenderProjectWithLastSetting",
                            ["r"] = "RenderProject",
                        }},
                ["n"] = "NextTab",
                ["p"] = "PrevTab",
                ["N"] = "PrevTab",
                ["s"] = "SaveProject",
                ["o"] = "OpenProject",
                ["c"] = "NewProjectTab",
                ["d"] = "CloseProject",
                ["x"] = "CleanProjectDirectory",
            }},
    }},
  },
}
