return {
  register_action = {
    ['"'] = "PasteRegister",
    ["yf"] = "SaveFxChain",
  },
  track_motion = {
    ["G"] = "LastTrack",
    ["gg"] = "FirstTrack",
    ["<down>"] = "NextFolderNear",
    ["<up>"] = "PrevFolderNear",
    ["J"] = "NextFolderNear",
    ["K"] = "PrevFolderNear",
    ["j"] = "NextTrack",
    ["k"] = "PrevTrack",
    ["<C-b>"] = "Prev10Track",
    ["<C-f>"] = "Next10Track",
    ["<C-d>"] = "Next5Track",
    ["<C-u>"] = "Prev5Track",
  },
  visual_track_command = {
    ["o"] = "SwitchTrackSelectionSide",
    ["V"] = "SetModeNormal",
  },
  track_selector = {
    ["V"] = "Selection",
    ["i"] = {"+inner", {
               ["f"] = "InnerFolder",
               ["g"] = "AllTracks",
    }},
    ["p"] = "SelectFolderParent",
  },
  track_operator = {
    ["z"] = "VerticalZoom",
    ["f"] = "MakeFolder",
    ["d"] = "CutTrack",
    ["a"] = "ArmToggle",
    ["s"] = "ToggleSolo",
    ["m"] = "ToggleMute",
    ["y"] = "CopyTrack",
    ["c"] = "ColorTrack",
  },
  timeline_operator = {
    ["s"] = "SelectItems",
    ["d"] = "DeleteItems",
    ["g"] = "GlueItems",
    ["r"] = "InsertRegion",
    ["y"] = "CopyItems",
    ["%"] = "HealSplits",
    [","] = "FitByLoopingNoShift",
    [";"] = {"+fit", {
       ["l"] = "FitByLooping",
       ["s"] = "FitByStretching",
       ["p"] = "FitByPadding",
    }},
  },
  timeline_selector = {
    ["s"] = "SelectedItems",
    ["v"] = "Selection",
    ["i"] = {"+inner", {
      ["r"] = "MarkerRegion",
      ["l"] = "AllTrackItems",
      ["p"] = "ProjectTimeline",
      ["w"] = "Item",
      ["W"] = "BigItem",
    }},
    ["n"] = "NextRegion",
    ["N"] = "PrevRegion",
    ["p"] = "PrevRegion",
  },
  timeline_motion = {
    ["B"] = "PrevBigItemStart",
    ["E"] = "NextBigItemEnd",
    ["W"] = "NextBigItemStart",
    ["b"] = "PrevItemStart",
    ["e"] = "NextItemEnd",
    ["w"] = "NextItemStart",
    ["<C-a>"] = "FirstItemStart",
    ["$"] = "LastItemEnd",
    ["g$"] = "ProjectEnd",
  },
  command = {
    ["<right>"] = "CycleFolderCollapsedState",
    ["<TAB>"] = "CycleFolderCollapsedState",
    ["<left>"] = "CycleFolderState",
    ["<S-TAB>"] = "CycleFolderState",
    ["<C-j>"] = "NextTrackKeepSel",
    ["<C-k>"] = "PrevTrackKeepSel",
    ["V"] = "SetModeVisualTrack",
    ["S"] = "UnselectItems",
    ["("] = "SetTimeSelectionStart",
    [")"] = "SetTimeSelectionEnd",
    ["+"] = "ZoomInHoriz",
    ["-"] = "ZoomOutHorizon",
    ["<"] = "GrowItemLeft",
    ["<M-j>"] = "NextEnvelope",
    ["<M-k>"] = "PrevEnvelope",
    ["<M-s>"] = "FxToggleShowAll",
    ["<C-+>"] = "ZoomInVert",
    ["<C-->"] = "ZoomOutVert",
    ["<C-<>"] = "ShrinkItemRight",
    ["<C->>"] = "ShrinkItemLeft",
    ["<C-N>"] = "FxShowPrevSel",
    ["<C-i>"] = "ZoomRedo",
    ["<C-m>"] = "TapTempo",
    ["<C-n>"] = "FxShowNextSel",
    ["<C-o>"] = "ZoomUndo",
    ["<C-p>"] = "FxShowPrevSel",
    ["<C-v>"] = "ToggleViewMixer",
    ["dd"] = "CutTrack",
    ["aa"] = "ArmToggle",
    ["dr"] = "DeleteRegion",
    ["ds"] = "DelEnvelopeInRegion",
    ["g;c"] = "SnapshotsAddNewAllTracks",
    ["O"] = "EnterTrackAbove",
    ["o"] = "EnterTrackBelow",
    ["p"] = "Paste",
    ["P"] = "PasteAbove",
    ["yf"] = "CopyFxChain",
    ["yy"] = "CopyTrack",
    ["zt"] = "ScrollToPlayPosition",
  },
}
