return {
  track_motion = {
    ["G"] = "LastTrack",
    ["gg"] = "FirstTrack",
    ["J"] = "NextFolderNear",
    ["K"] = "PrevFolderNear",
    ["j"] = "NextTrack",
    ["k"] = "PrevTrack",
    ["<C-b>"] = "Prev10Track",
    ["<C-d>"] = "Next5Track",
    ["<C-u>"] = "Prev5Track",
  },
  visual_track_command = {
    ["o"] = "SwitchTrackSelectionSide",
  },
  track_selector = {
    ["i"] = {"+inner", {
               ["f"] = "InnerFolder",
               ["g"] = "AllTracks",
    }},
    ["o"] = {"+outer", {
               ["f"] = "OuterFolder"
    }},
  },
  track_operator = {
    ["z"] = "VerticalZoom",
    ["f"] = "MakeFolder",
    ["d"] = "CutTrack",
    ["a"] = "ArmToggle",
    ["s"] = "ToggleSolo",
    ["m"] = "ToggleMute",
    ["y"] = "CopyTrack",
    ["c"] = "ColorTrack",
  },
  timeline_operator = {
    ["s"] = "SelectItems",
    ["d"] = "DeleteItems",
    ["g"] = "GlueItems",
    ["r"] = "InsertRegion",
    ["y"] = "CopyItems",
  },
  timeline_selector = {
    ["s"] = "SelectedItems",
    ["i"] = {"+inner", {
      ["r"] = "Region",
      ["l"] = "AllTrackItems",
      ["p"] = "ProjectTimeline",
      ["w"] = "Item",
      ["W"] = "BigItem",
    }},
    ["o"] = {"+outer", {
      ["l"] = "ProjectTimeline",
      ["$"] = "ProjectTimeline",
    }},
    ["n"] = "NextRegion",
    ["N"] = "PrevRegion",
    ["p"] = "PrevRegion",
  },
  timeline_motion = {
    ["B"] = "PrevBigItemStart",
    ["E"] = "NextBigItemEnd",
    ["W"] = "NextBigItemStart",
    ["b"] = "PrevItemStart",
    ["e"] = "NextItemEnd",
    ["w"] = "NextItemStart",
    ["<C-a>"] = "FirstItemStart",
    ["$"] = "LastItemEnd",
    ["g$"] = "ProjectEnd",
  },
  command = {
    ["<C-j>"] = "NextTrackKeepSel",
    ["<C-k>"] = "PrevTrackKeepSel",
    ["aa"] = "ArmToggle",
    ["<TAB>"] = "CycleFolderCollapsedState",
    ["<C-TAB>"] = "CycleFolderState",
    ["V"] = "ToggleVisualTrackMode",
    ["S"] = "UnselectItems",
    ["%"] = "CropToActiveTake",
    ["("] = "SetTimeSelectionStart",
    [")"] = "SetTimeSelectionEnd",
    ["+"] = "ZoomInHoriz",
    ["-"] = "ZoomOutHorizon",
    ["<"] = "GrowItemLeft",
    ["<M-j>"] = "NextEnvelope",
    ["<M-k>"] = "PrevEnvelope",
    ["<M-s>"] = "FxToggleShowAll",
    ["<M-w>"] = "FocusMain",
    ["<C-+>"] = "ZoomInVert",
    ["<C-->"] = "ZoomOutVert",
    ["<C-<>"] = "ShrinkItemRight",
    ["<C->>"] = "ShrinkItemLeft",
    ["<C-N>"] = "FxShowPrevSel",
    ["<C-i>"] = "ZoomRedo",
    ["<C-m>"] = "TapTempo",
    ["<C-n>"] = "FxShowNextSel",
    ["<C-o>"] = "ZoomUndo",
    ["<C-p>"] = "FxShowPrevSel",
    ["<C-v>"] = "ToggleViewMixer",
    ["P"] = "PasteAbove",
    ["_"] = "DeleteActiveTake",
    ["dd"] = "CutTrack",
    ["dr"] = "DeleteRegion",
    ["ds"] = "DelEnvelopeInRegion",
    ["fN"] = "RegionSelectPrev",
    ["fn"] = "RegionSelectNext",
    ["fp"] = "RegionSelectPrev",
    ["g;c"] = "SnapshotsAddNewAllTracks",
    ["O"] = "EnterTrackAbove",
    ["o"] = "EnterTrackBelow",
    ["p"] = "Paste",
    ["r<SPC>f"] = "ExpandItemsToRegion",
    ["r<SPC>s"] = "RegionSplitItems",
    ["x"] = "CutItem",
    ["yf"] = "CopyFxChain",
    ["yy"] = "CopyTrack",
    ["z"] = { "+zoom/view", {
              ["p"] = "ZoomProject",
              ["1"] = "TrackView.Load_1",
              ["2"] = "TrackView.Load_2",
              ["3"] = "TrackView.Load_3",
              ["4"] = "TrackView.Load_4",
              ["5"] = "TrackView.Load_5",
              ["6"] = "TrackView.Load_6",
              ["7"] = "TrackView.Load_7",
              ["8"] = "TrackView.Load_8",
              ["9"] = "TrackView.Load_9",
              ["m1"] = "TrackView.Save_1",
              ["m2"] = "TrackView.Save_2",
              ["m3"] = "TrackView.Save_3",
              ["m4"] = "TrackView.Save_4",
              ["m5"] = "TrackView.Save_5",
              ["m6"] = "TrackView.Save_6",
              ["m7"] = "TrackView.Save_7",
              ["m8"] = "TrackView.Save_8",
              ["m9"] = "TrackView.Save_9",
              ["<TAB>"] = "ZoomFolder",
              ["t"] = "ZoomTrackSelection",
              ["f"] = "ZoomToPlayPosition",
              ["is"] = "ZoomItemSelection",
              ["ig"] = "ZoomAllTracks",
              ["r"] = "ZoomHorizontal",
              ["s"] = "ZoomTimeAndTrackSelection",
              ["z"] = "ScrollToSelectedTrack",
    }},
    ["{"] = "PrevTake",
    ["}"] = "NextTake",
  },
}
