# frozen_string_literal: true

module KeyDefinitions
  CONTEXTS = Hash[
    midi: 32_060,
    main: 0
  ]
  KEY_MODS = Hash[
    # C -> ctrl, M -> alt, S -> shift
    C: 9,
    M: 17,
    S: 5,
    MS: 21,
    CS: 13,
    CM: 25,
    CMS: 29,
  ]
  ALIASES = Hash[
    "." => "period",
    ":" => "colon",
    "," => "comma",
    "-" => "hyphen",
    "_" => "underscore",
    ";" => "semicolon",
    "?" => "questionmark",
    "+" => "plus",
    "!" => "exclamation",
    "'" => "apostrophe",
    "\\" => "backslash",
    "|" => "pipe",
    "/" => "slash",
    "#" => "numbersign",
    "@" => "at",
    "§" => "sectionsign",
    "~" => "tilde",
    "±" => "plusminus",
    "]" => "closebracket",
    "[" => "openbracket",
    "(" => "openparen",
    ")" => "closeparen",
    "$" => "dollar",
    "%" => "percent",
    "&" => "ampersand",
    "\"" => "quotation",
    "}" => "closewing",
    "{" => "openwing",
    "=" => "equals",
    "`" => "backtick",
  ]
  KEY_TABLE = Hash[
    special: Hash[
      key_type_id: 1,
      keys: Hash[
        '(' => 40,
        "'" => 222,
        '"' => 124,
        '!' => 113,
        '<space>' => 32,
        '<backspace>' => 8,
        '<ESC>' => 27,
        '<tab>' => 9,
        '<hook>' => 223,
        '<left>' => 37,
        '<up>' => 32_806,
        '<right>' => 32_807,
        '<down>' => 32_808,
      ]
    ],
    normal: Hash[
      key_type_id: 0,
      keys: Hash[
        '<return>' => 13,
        '<f1>' => 112,
        '<f2>' => 113,
        '<f3>' => 114,
        '<f4>' => 115,
        '<f5>' => 116,
        '<f6>' => 117,
        '<f7>' => 118,
        '<f8>' => 119,
        '<f9>' => 120,
        '<f10>' => 121,
        '.' => 46,
        '<' => 60,
        '>' => 62,
        ':' => 58,
        ',' => 44,
        '-' => 45,
        '_' => 95,
        ';' => 59,
        '?' => 63,
        '+' => 43,
        '\\' => 220,
        '|' => 220,
        '/' => 47,
        '#' => 35,
        '@' => 64,
        '§' => 167,
        '~' => 126,
        '±' => 177,
        ']' => 93,
        '[' => 91,
        '}' => 125,
        '{' => 123,
        '=' => 61,
        '`' => 96,
        ')' => 41,
        '$' => 36,
        '%' => 37,
        '&' => 55,
        'a' => 65,
        'b' => 66,
        'c' => 67,
        'd' => 68,
        'e' => 69,
        'f' => 70,
        'g' => 71,
        'h' => 72,
        'i' => 73,
        'j' => 74,
        'k' => 75,
        'l' => 76,
        'm' => 77,
        'n' => 78,
        'o' => 79,
        'p' => 80,
        'q' => 81,
        'r' => 82,
        's' => 83,
        't' => 84,
        'u' => 85,
        'v' => 86,
        'w' => 87,
        'x' => 88,
        'y' => 89,
        'z' => 90,
        '0' => 48,
        '1' => 49,
        '2' => 50,
        '3' => 51,
        '4' => 52,
        '5' => 53,
        '6' => 54,
        '7' => 55,
        '8' => 56,
        '9' => 57
      ]
    ]
  ]
end
